SELECT
    SUBSTR(R.RESERV_DATE, 1, 6) AS MONTH,
    
    SUM(CASE WHEN I.PRODUCT_NAME = 'SPECIAL_SET'
             THEN O.SALES ELSE 0 END) AS SPECIAL_SET,
             
    SUM(CASE WHEN I.PRODUCT_NAME = 'PASTA'
             THEN O.SALES ELSE 0 END) AS PASTA,
    
    SUM(CASE WHEN I.PRODUCT_NAME = 'PIZZA'
             THEN O.SALES ELSE 0 END) AS PIZZA,

    SUM(CASE WHEN I.PRODUCT_NAME = 'SEA_FOOD'
             THEN O.SALES ELSE 0 END) AS SEA_FOOD,

    SUM(CASE WHEN I.PRODUCT_NAME = 'STEAK'
             THEN O.SALES ELSE 0 END) AS STEAK,

    SUM(CASE WHEN I.PRODUCT_NAME = 'SALAD_BAR'
             THEN O.SALES ELSE 0 END) AS SALAD_BAR,

    SUM(CASE WHEN I.PRODUCT_NAME = 'SALAD'
             THEN O.SALES ELSE 0 END) AS SALAD,

    SUM(CASE WHEN I.PRODUCT_NAME = 'SANDWICH'
             THEN O.SALES ELSE 0 END) AS SANDWICH,

    SUM(CASE WHEN I.PRODUCT_NAME = 'WINE'
             THEN O.SALES ELSE 0 END) AS WINE,

    SUM(CASE WHEN I.PRODUCT_NAME = 'JUICE'
             THEN O.SALES ELSE 0 END) AS JUICE
             
FROM RESERVATION R
JOIN ORDER_INFO O
    ON R.RESERV_NO = O.RESERV_NO
JOIN ITEM I
    ON O.ITEM_ID = I.ITEM_ID
GROUP BY SUBSTR(R.RESERV_DATE, 1, 6)
ORDER BY MONTH
