SELECT
    MONTH,
    NVL(SPECIAL_SET, 0) AS SPECIAL_SET,
    NVL(PASTA, 0) AS PASTA,
    NVL(PIZZA, 0) AS PIZZA,
    NVL(SEA_FOOD, 0) AS SEA_FOOD,
    NVL(STEAK, 0) AS STEAK,
    NVL(SALAD_BAR, 0) AS SALAD_BAR,
    NVL(SALAD, 0) AS SALAD,
    NVL(SANDWICH, 0) AS SANDWICH,
    NVL(WINE, 0) AS WINE,
    NVL(JUICE, 0) AS JUICE
FROM (
    SELECT
        SUBSTR(R.RESERV_DATE, 1, 6) AS MONTH,
        I.PRODUCT_NAME,
        O.SALES
    FROM RESERVATION R
    JOIN ORDER_INFO O
        ON R.RESERV_NO = O.RESERV_NO
    JOIN ITEM I
        ON O.ITEM_ID = I.ITEM_ID
)
PIVOT (
    SUM(SALES)
    FOR PRODUCT_NAME IN (
        'SPECIAL_SET' AS SPECIAL_SET,
        'PASTA' AS PASTA,
        'PIZZA' AS PIZZA,
        'SEA_FOOD' AS SEA_FOOD,
        'STEAK' AS STEAK,
        'SALAD_BAR' AS SALAD_BAR,
        'SALAD' AS SALAD,
        'SANDWICH' AS SANDWICH,
        'WINE' AS WINE,
        'JUICE' AS JUICE
    )
)
ORDER BY MONTH;
